# Service for the backend-app, exposed via NodePort

apiVersion: v1

kind: Service

metadata:

  name: frontend-app-service

spec:

  type: NodePort

  selector:

    tier: frontend

  ports:

    - protocol: TCP

      port: 9777 # Service port

      nodePort: 30009 # Nodeport - laptop port

      targetPort: 80 # Pod port

---

# Service for the frontend-app, exposed via LoadBalancer

apiVersion: v1

kind: Service

metadata:

  name: frontend-app-lb


spec:

  type: LoadBalancer

  selector:

    tier: frontend

  ports:

    - protocol: TCP

      port: 8080 # Service port

      targetPort: 80 # Pod port
