apiVersion: v1

kind: Service

metadata:

  name: frontend-app-service

spec:

  type: NodePort

  selector:

    tier: frontend

  ports:

    - protocol: TCP

      port: 9777 # service port

      nodePort: 30009 # nodeport - laptop port 

      targetPort: 80 # pod port

  metadata:

  name: frontend-app-lb

  annotations:

    service.beta.kubernetes.io/azure-load-balancer-ipv4: "74.225.176.40"

  spec:

    type: LoadBalancer

    selector:

    tier: frontend

    ports:

    - protocol: TCP

      port: 8080 # service port

      targetPort: 80 # pod port

